again

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -92,6 +92,9 @@ jobs:
   build:
       runs-on: self-hosted
       needs: setup
+      outputs:
+        BUILD_STATUS: ${{ steps.set_build_status.outputs.status }}
+        BUILD_ERROR: ${{ steps.set_build_status.outputs.error }}
       steps:
 
       #original
@@ -121,10 +124,7 @@ jobs:
       - name: Build Application
         id: build_step
         run: |
-          BUILD_OUTPUT=$(mvn spring-javaformat:apply && mvn clean package 2>&1) || {
-            echo "$BUILD_OUTPUT" > build_error.log;
-            exit 1;
-          }
+          BUILD_OUTPUT=$(mvn spring-javaformat:apply && mvn clean package 2>&1)
         continue-on-error: true
 
       - name: Capture Build Result
@@ -134,9 +134,9 @@ jobs:
             echo "BUILD_STATUS=Success" >> $GITHUB_ENV
             echo "BUILD_ERROR=" >> $GITHUB_ENV
           else
-            ERROR_MESSAGE=$(<build_error.log)
             echo "BUILD_STATUS=Failed" >> $GITHUB_ENV
-            echo "BUILD_ERROR=$ERROR_MESSAGE" >> $GITHUB_ENV
+            echo "BUILD_ERROR=$BUILD_OUTPUT" >> $GITHUB_ENV
+            exit 1
           fi
 
   setup2:
