complete pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -63,6 +63,76 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
+  Prebuild-sonarScannerCloudScan:
+    runs-on: self-hosted
+    needs: setup
+    outputs:
+      TASK_ID: ${{ steps.extract_task_id.outputs.task_id }} # Define el output
+    steps:
+      - name: Run SonarScanner
+        env:
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+            SONAR_PROJECT_KEY: ignasijuez_github
+            SONAR_ORGANIZATION: ignasijuez
+        run: |
+          sonar-scanner \
+            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
+            -Dsonar.organization=${SONAR_ORGANIZATION} \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.login=${SONAR_TOKEN} \
+            -Dsonar.sources=src \
+            -Dsonar.exclusions=**/*.java \
+            -Dsonar.java.binaries=none \
+            -Dsonar.qualitygate.wait=false
+
+      #- name: Locate report-task.txt
+      #  run: find . -name "report-task.txt"
+
+      - name: Extract SonarCloud Task ID
+        id: extract_task_id
+        run: |
+          if [ ! -f .scannerwork/report-task.txt ]; then
+            echo "SonarCloud report-task.txt not found!"
+            exit 1
+          fi
+          task_id=$(grep 'ceTaskId' .scannerwork/report-task.txt | cut -d '=' -f 2)
+          echo "Task ID (local): $task_id"
+          echo "::set-output name=task_id::$task_id"
+        continue-on-error: false
+
+  Prebuild-Dependency-Analysis:
+    runs-on: self-hosted
+    needs: setup
+    steps:
+      - name: Run OWASP Dependency Check
+        id: dependency_check
+        run: |
+          mvn org.owasp:dependency-check-maven:check \
+              -Dformat=HTML \
+              -DautoUpdate=false \
+              -Dexcludes=com.h2database:h2 \
+              -DfailBuildOnCVSS=1.0 \
+              -DoutputDirectory=dependency-check-report #|| exit_code=$?
+          #echo "exit_code=$exit_code" >> $GITHUB_ENV
+        continue-on-error: true
+
+      - name: Upload Dependency-Check Report
+        if: always() # Esto asegura que el informe se suba incluso si el análisis falla
+        uses: actions/upload-artifact@v3
+        with:
+          name: dependency-check-report
+          path: dependency-check-report/
+      
+      # Determine Dependency-Check Result
+      - name: Determine Dependency Check Result
+        run: |
+          if [ "${{ env.exit_code }}" -ne 0 ]; then
+            echo "Dependency validation failed. Vulnerabilities detected!"
+            echo "UNSTABLE: Dependency validation did not pass."
+          else
+            echo "STABLE: Dependency validation passed successfully."
+          fi
+
   build:
       runs-on: self-hosted
       needs: setup
@@ -126,6 +196,64 @@ jobs:
           context: .
           push: true
           tags: juezignasi/ga-app:latest
+
+  Check-SonarCloud-Results:
+    runs-on: self-hosted
+    needs: [docker-build-push, Prebuild-sonarScannerCloudScan]
+    steps:
+      - name: Check SonarCloud Task Status
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          TASK_ID: ${{ needs.Prebuild-sonarScannerCloudScan.outputs.TASK_ID }}
+        run: |
+          if [ -z "$TASK_ID" ]; then
+            echo "No Task ID found, skipping SonarCloud status check."
+            exit 1
+          fi
+          
+          echo "Checking status for Task ID: $TASK_ID"
+
+          status=""
+          timeoutMinutes=10
+          pollIntervalSeconds=15
+          elapsedTime=0
+          
+          # Poll SonarCloud until the task is completed
+          while [ "$elapsedTime" -lt $((timeoutMinutes * 60)) ]; do
+            response=$(curl -s -H "Authorization: Bearer $SONAR_TOKEN" "https://sonarcloud.io/api/ce/task?id=$TASK_ID")
+            status=$(echo $response | jq -r '.task.status')
+            echo "SonarCloud task status: $status"
+            
+            if [ "$status" == "SUCCESS" ]; then
+              echo "SonarCloud analysis completed successfully."
+              break
+            elif [ "$status" == "FAILED" ]; then
+              echo "SonarCloud analysis failed!"
+              exit 1
+            fi
+            
+            sleep $pollIntervalSeconds
+            elapsedTime=$((elapsedTime + pollIntervalSeconds))
+          done
+
+          if [ "$status" != "SUCCESS" ]; then
+            echo "SonarCloud analysis did not complete in time!"
+            exit 1
+          fi
+
+          echo "SonarCloud analysis completed. Fetching Quality Gate status..."
+
+          # Check Quality Gate status
+          response=$(curl -s -H "Authorization: Bearer $SONAR_TOKEN" "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$(echo $response | jq -r '.task.analysisId')")
+          quality_gate_status=$(echo $response | jq -r '.projectStatus.status')
+          echo "SonarCloud Quality Gate Status: $quality_gate_status"
+
+          if [ "$quality_gate_status" != "OK" ]; then
+            echo "SonarCloud Quality Gate failed!"
+            exit 1
+          fi
+
+          echo "SonarCloud Quality Gate passed successfully."
 
   deploy-mysql:
     runs-on: self-hosted
