test logs

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -34,34 +34,39 @@ jobs:
             exit 1
           fi
 
-      - name: checkout
-        uses: actions/checkout@v4 #predefined action from the marketplace
-        with: 
-          repository: ${{ inputs.REPO_URL }}
-          ref: ${{ inputs.BRANCH }}
+      # option 1
+      #- name: checkout
+      #  uses: actions/checkout@v4 #predefined action from the marketplace
+      #  with: 
+      #    repository: ${{ inputs.REPO_URL }}
+      #    ref: ${{ inputs.BRANCH }}
 
-      - name: HTTP Request on Success
-        if: success()
+      #- name: Capture Checkout Result
+      #  run: |
+      #    if [[ -z "${{ steps.checkout.outcome }}" ]]; then
+      #      echo "CHECKOUT_STATUS=Success" >> $GITHUB_ENV
+      #    else
+      #      echo "CHECKOUT_STATUS=Failed" >> $GITHUB_ENV
+      #      echo "CHECKOUT_ERROR=${{ steps.checkout.outcome }}" >> $GITHUB_ENV
+      #      exit 1
+      #    fi
+        
+      # option 2
+      - name: Checkout Repository
+        id: checkout
         run: |
-          curl -X POST https://httpbin.org/post \
-          -H "Content-Type: application/json" \
-          -d '{
-            "job": "checkout",
-            "status": "Success",
-            "details": "Checkout completed successfully"
-          }'
-      
-      - name: HTTP Request on Failure
-        if: failure()
+          CHECKOUT_OUTPUT=$(git clone ${{ inputs.REPO_URL }} -b ${{ inputs.BRANCH }} 2>&1) || echo "$CHECKOUT_OUTPUT" > checkout_error.log
+        continue-on-error: true
+
+      - name: Capture Checkout Result
         run: |
-          ERROR_MESSAGE="Checkout failed. Error in step: ${{ steps.checkout_step.outcome }}"
-          curl -X POST https://httpbin.org/post \
-            -H "Content-Type: application/json" \
-            -d "{
-              \"job\": \"checkout\",
-              \"status\": \"Failed\",
-              \"details\": \"${ERROR_MESSAGE}\"
-            }"
+          if [[ -z "${{ steps.checkout.outcome }}" ]]; then
+            echo "CHECKOUT_STATUS=Success" >> $GITHUB_ENV
+          else
+            ERROR_MESSAGE=$(<checkout_error.log)
+            echo "CHECKOUT_STATUS=Failed" >> $GITHUB_ENV
+            echo "CHECKOUT_ERROR=${ERROR_MESSAGE}" >> $GITHUB_ENV
+            exit 1
 
   setup:
     runs-on: self-hosted
